### ISSUE TITLE
sridhar data

### ISSUE THREAD

**Issue by mjstrumillo** [WahlinLab/Human_RGC-iN#1]
hi, Im trying to obtain the additional reference datasets and in [Human_RGC-iN]/[sc_data]/sridhar_fetal_rgcs/ 
there are 7970 barcodes and 33694 genes, however the matrix size is 33694x3335 - could you advise about the barcodes that match the matrix please?

**Comment by recursivelymanan** [comment]
Hi @mjstrumillo !

Very sorry for the extremely late response, but there is indeed a discrepancy. It seems that the `barcodes.tsv` file got mixed up somewhere along the way. I've just pushed a fix. 

Thanks for catching that, and sorry again for the delay!
